openapi: 3.0.3
info:
  title: NextSmartShip openapi
  version: '1.0'
servers:
- url: https://openapi.dev.nextsmartship.com
  variables:
    version:
      default: v1
paths:
  /shipping-estimate:
    get:
      tags:
      - quote
      summary: get quote
      operationId: quote#get
      parameters:
      - name: origin_country
        in: query
        description: Origin country code (two-letter codes)
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Origin country code (two-letter codes)
          example: CN
          minLength: 2
          maxLength: 2
        example: CN
      - name: dest_country
        in: query
        description: Destination country code (two-letter codes)
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Destination country code (two-letter codes)
          example: US
          minLength: 2
          maxLength: 2
        example: US
      - name: dest_state
        in: query
        description: State of destination country
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: State of destination country
          example: NY
        example: NY
      - name: dest_zip_code
        in: query
        description: Destination post code
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Destination post code
          example: "10016"
        example: "10016"
      - name: weight
        in: query
        description: total weight of the package, unit(g)
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: total weight of the package, unit(g)
          example: 3000
          minimum: 1
        example: 3000
      - name: length
        in: query
        description: the length of the package, unit(mm)
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: the length of the package, unit(mm)
          example: 100
          minimum: 1
        example: 100
      - name: width
        in: query
        description: the width of the package, unit(mm)
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: the width of the package, unit(mm)
          example: 200
          minimum: 1
        example: 200
      - name: height
        in: query
        description: the height of the package, unit(mm)
        allowEmptyValue: true
        required: true
        schema:
          type: integer
          description: the height of the package, unit(mm)
          example: 300
          minimum: 1
        example: 300
      - name: product_attributes
        in: query
        description: Product attributes
        allowEmptyValue: true
        required: true
        schema:
          type: array
          items:
            type: string
          description: Product attributes
          example:
          - battery
          - cosmetic
          - liquid
          - magnetic
        example:
        - battery
        - cosmetic
        - liquid
        - magnetic
      - name: factory
        in: query
        description: address of factory
        allowEmptyValue: true
        schema:
          type: string
          description: address of factory
          example: 江苏省
        example: 江苏省
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
                example:
                - channel_id: 1
                  channel_name: NSS
                  currency: USD
                  max_normal_days: 5
                  min_normal_days: 3
                  total_cost: 45.89
                  type: 1
                  weight: 1000
                - channel_id: 1
                  channel_name: NSS
                  currency: USD
                  max_normal_days: 5
                  min_normal_days: 3
                  total_cost: 45.89
                  type: 1
                  weight: 1000
              example:
              - channel_id: 1
                channel_name: NSS
                currency: USD
                max_normal_days: 5
                min_normal_days: 3
                total_cost: 45.89
                type: 1
                weight: 1000
              - channel_id: 1
                channel_name: NSS
                currency: USD
                max_normal_days: 5
                min_normal_days: 3
                total_cost: 45.89
                type: 1
                weight: 1000
              - channel_id: 1
                channel_name: NSS
                currency: USD
                max_normal_days: 5
                min_normal_days: 3
                total_cost: 45.89
                type: 1
                weight: 1000
components:
  schemas:
    Quote:
      type: object
      properties:
        channel_id:
          type: integer
          description: Channel ID
          example: 1
          format: int32
        channel_name:
          type: string
          description: Channel Display Name
          example: NSS
        currency:
          type: string
          example: USD
        max_normal_days:
          type: integer
          description: Max Normal Days
          example: 5
          format: int32
        min_normal_days:
          type: integer
          description: Min Normal Days
          example: 3
          format: int32
        total_cost:
          type: number
          description: Total cost (decimal(15,2))
          example: 45.89
          format: double
        type:
          type: integer
          description: Channel type
          example: 1
          format: int64
        weight:
          type: integer
          description: weight(unit g)
          example: 1000
          format: int64
      example:
        channel_id: 1
        channel_name: NSS
        currency: USD
        max_normal_days: 5
        min_normal_days: 3
        total_cost: 45.89
        type: 1
        weight: 1000
      required:
      - channel_name
      - channel_id
      - type
      - min_normal_days
      - max_normal_days
      - total_cost
      - currency
      - weight
tags:
- name: quote
  description: The quote service performs operations on quotation